version: 2

sources:
  - name: sap_adw
    description: fonte erp sap Adventures Works
    tables:
      - name: address
      - name: stateprovince   
      - name: countryregion
      - name: customer
      - name: person
      - name: salesorderheadersalesreason
      - name: salesreason